package com.aresstack.winacp.acp;

import com.aresstack.winacp.config.*;
import com.aresstack.winacp.graph.LangGraphAgentRunner;
import com.aresstack.winacp.inference.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * End-to-end test: ACP session/prompt → LangGraph4j with INFER node → InferenceEngine → response.
 * <p>
 * This is the critical-path smoke test:
 * <ol>
 *   <li>ACP Client sends {@code initialize}</li>
 *   <li>ACP Client sends {@code session/new}</li>
 *   <li>ACP Client sends {@code session/prompt}</li>
 *   <li>Agent runs graph with INFER node</li>
 *   <li>INFER node calls InferenceEngine.generate()</li>
 *   <li>Agent responds via {@code session/update}</li>
 *   <li>Agent returns {@code stopReason: end_turn}</li>
 * </ol>
 */
class AcpInferenceEndToEndTest {

    private static final ObjectMapper mapper = new ObjectMapper();

    @Test
    void fullFlow_acpPrompt_throughInferNode_producesRealResponse() throws Exception {
        // --- Setup: custom inference engine with predictable output ---
        InferenceEngine testEngine = new InferenceEngine() {
            private boolean ready = false;
            @Override public void initialize() { ready = true; }
            @Override public void shutdown() { ready = false; }
            @Override public boolean isReady() { return ready; }
            @Override
            public InferenceResult generate(InferenceRequest request) {
                // Verify the request contains what we expect
                assertFalse(request.getUserPrompt().isEmpty());
                return new InferenceResult(
                        "The answer is 42. This response was generated by the inference engine.",
                        "end_turn",
                        new InferenceResult.Usage(8, 12, 20));
            }
        };
        testEngine.initialize();

        // --- Build graph with INFER node ---
        LangGraphAgentRunner runner = new LangGraphAgentRunner(inferBehavior());
        runner.setInferenceEngine(testEngine);
        runner.registerDefaults();

        // --- Wire ACP server with pipes ---
        PipedOutputStream clientOut = new PipedOutputStream();
        PipedInputStream serverIn = new PipedInputStream(clientOut);
        ByteArrayOutputStream serverOut = new ByteArrayOutputStream();

        String systemRole = "You are a helpful test assistant.";
        AcpAgentServer server = new AcpAgentServer(runner, systemRole, serverIn, serverOut);

        Thread serverThread = new Thread(server::start, "e2e-infer-server");
        serverThread.setDaemon(true);
        serverThread.start();

        // --- Client: initialize ---
        clientOut.write(frame(jsonRpc(1, "initialize", "{\"protocolVersion\":1}")));
        clientOut.flush();
        Thread.sleep(200);

        // --- Client: session/new ---
        clientOut.write(frame(jsonRpc(2, "session/new", "{\"cwd\":\".\",\"mcpServers\":[]}")));
        clientOut.flush();
        Thread.sleep(200);

        // Extract sessionId
        String outputSoFar = serverOut.toString(StandardCharsets.UTF_8);
        List<JsonNode> responses = parseAll(outputSoFar);
        assertTrue(responses.size() >= 2, "should have init + session/new responses");
        String sessionId = responses.get(1).path("result").path("sessionId").asText();
        assertFalse(sessionId.isEmpty());

        // --- Client: session/prompt ---
        String promptReq = jsonRpc(3, "session/prompt",
                "{\"sessionId\":\"" + sessionId + "\"," +
                "\"prompt\":[{\"type\":\"text\",\"text\":\"What is the meaning of life?\"}]}");
        clientOut.write(frame(promptReq));
        clientOut.flush();
        Thread.sleep(500);

        // Close to terminate server
        clientOut.close();
        serverThread.join(3000);

        // --- Verify output ---
        String fullOutput = serverOut.toString(StandardCharsets.UTF_8);
        List<JsonNode> allMessages = parseAll(fullOutput);

        // Find session/prompt response (id=3)
        JsonNode promptResponse = allMessages.stream()
                .filter(m -> m.has("id") && m.get("id").asInt() == 3)
                .findFirst().orElse(null);
        assertNotNull(promptResponse, "should have prompt response");
        assertEquals("end_turn", promptResponse.path("result").path("stopReason").asText());

        // Find session/update notification with the inference result
        JsonNode updateNotif = allMessages.stream()
                .filter(m -> "session/update".equals(m.path("method").asText()))
                .findFirst().orElse(null);
        assertNotNull(updateNotif, "should have session/update notification");

        String agentText = updateNotif.path("params").path("update").path("content").path("text").asText();
        assertTrue(agentText.contains("42"),
                "session/update should contain the inference engine's response");

        testEngine.shutdown();
    }

    @Test
    void fullFlow_withStubEngine_alsoWorks() throws Exception {
        StubInferenceEngine stubEngine = new StubInferenceEngine();
        stubEngine.initialize();

        LangGraphAgentRunner runner = new LangGraphAgentRunner(inferBehavior());
        runner.setInferenceEngine(stubEngine);
        runner.registerDefaults();

        // Use direct handleRequest for simplicity
        AcpAgentServer server = new AcpAgentServer(runner, "You are a test bot.");
        String response = server.handleRequest("Hello, how are you?");

        assertNotNull(response);
        assertTrue(response.contains("[stub]"),
                "with stub engine, response should contain stub marker");

        stubEngine.shutdown();
    }

    // ---- helpers ----

    private AgentBehaviorDefinition inferBehavior() {
        var behavior = new AgentBehaviorDefinition();
        behavior.setStartNode("analyze");
        behavior.setMaxIterations(10);
        behavior.setNodes(new ArrayList<>(List.of(
                node("analyze", NodeType.ANALYZE_INPUT),
                node("goal", NodeType.DETERMINE_GOAL),
                node("infer", NodeType.INFER),
                node("respond", NodeType.FORMULATE_RESPONSE),
                node("finalize", NodeType.FINALIZE)
        )));
        behavior.setEdges(new ArrayList<>(List.of(
                edge("analyze", "goal", RoutingCondition.ALWAYS),
                edge("goal", "infer", RoutingCondition.ALWAYS),
                edge("infer", "respond", RoutingCondition.ALWAYS),
                edge("respond", "finalize", RoutingCondition.ALWAYS)
        )));
        return behavior;
    }

    private String jsonRpc(int id, String method, String params) {
        return "{\"jsonrpc\":\"2.0\",\"id\":" + id +
                ",\"method\":\"" + method + "\",\"params\":" + params + "}";
    }

    private byte[] frame(String json) {
        byte[] body = json.getBytes(StandardCharsets.UTF_8);
        String header = "Content-Length: " + body.length + "\r\n\r\n";
        byte[] h = header.getBytes(StandardCharsets.UTF_8);
        byte[] r = new byte[h.length + body.length];
        System.arraycopy(h, 0, r, 0, h.length);
        System.arraycopy(body, 0, r, h.length, body.length);
        return r;
    }

    private List<JsonNode> parseAll(String raw) throws Exception {
        List<JsonNode> messages = new ArrayList<>();
        int pos = 0;
        while (pos < raw.length()) {
            int cl = raw.indexOf("Content-Length:", pos);
            if (cl < 0) break;
            int eol = raw.indexOf("\r\n", cl);
            if (eol < 0) break;
            int len = Integer.parseInt(raw.substring(cl + 15, eol).trim());
            int start = raw.indexOf("\r\n\r\n", cl);
            if (start < 0) break;
            start += 4;
            if (start + len > raw.length()) break;
            messages.add(mapper.readTree(raw.substring(start, start + len)));
            pos = start + len;
        }
        return messages;
    }

    private NodeDefinition node(String id, NodeType type) {
        var n = new NodeDefinition();
        n.setId(id);
        n.setType(type);
        return n;
    }

    private EdgeDefinition edge(String from, String to, RoutingCondition cond) {
        var e = new EdgeDefinition();
        e.setFrom(from);
        e.setTo(to);
        e.setCondition(cond);
        return e;
    }
}

